apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    name: kafka
  type: ClusterIP
  clusterIP: None
