apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: clientport
      port: 2181
      targetPort: 2181
      protocol: TCP
  selector:
    name: zookeeper
  type: ClusterIP
