apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  ports:
    - name: clientport
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: clustering
      port: 2888
      targetPort: 2888
      protocol: TCP
    - name: leaderelection
      port: 3888
      targetPort: 3888
      protocol: TCP
  selector:
    name: zookeeper
  type: ClusterIP
  clusterIP: None
