apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper-headless"
  replicas: 3
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /var/lib/zookeeper/"]
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper
      containers:
        - name: zookeeper
          image: "enmasseproject/zookeeper:latest"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
            - name: clustering
              containerPort: 2888
              protocol: TCP
            - name: leaderelection
              containerPort: 3888
              protocol: TCP
          env:
            - name: ZOOKEEPER_NODE_COUNT
              value: "3"
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper
          livenessProbe:
            exec:
              command:
              - "/opt/zookeeper/zookeeper_healthcheck.sh"
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - "/opt/zookeeper/zookeeper_healthcheck.sh"
            initialDelaySeconds: 15
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
