---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-topic-controller
  labels:
    app: strimzi
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: strimzi-topic-controller-role
  labels:
    app: strimzi
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: strimzi-topic-controller-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-topic-controller
roleRef:
  kind: ClusterRole
  name: strimzi-topic-controller-role
apiGroup: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-topic-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-topic-controller
    spec:
      serviceAccountName: strimzi-topic-controller
      containers:
        - name: strimzi-topic-controller
          image: strimzi/topic-controller:latest
          env:
            - name: TC_CM_LABELS
              value: "strimzi.io/kind=topic"
            - name: TC_ZK_SESSION_TIMEOUT
              value: "2seconds"
            - name: TC_PERIODIC_INTERVAL
              value: "15minutes"
