---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkausers.kafka.strimzi.io
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    singular: kafkauser
    plural: kafkausers
    shortNames:
    - ku
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            authentication:
              type: object
              properties:
                additionalProperties:
                  type: object
                tls:
                  type: object
                  properties:
                    additionalProperties:
                      type: object
            additionalProperties:
              type: object
          required:
          - authentication
        additionalProperties:
          type: object
      required:
      - spec
