---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkausers.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    singular: kafkauser
    plural: kafkausers
    shortNames:
    - ku
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            authentication:
              type: object
              properties:
                type:
                  type: string
            authorization:
              type: object
              properties:
                acls:
                  type: array
                  items:
                    type: object
                    properties:
<<<<<<< HEAD
<<<<<<< HEAD
=======
                      group:
                        type: string
>>>>>>> Add Authorization section to KafkaUser CRD
=======
>>>>>>> Update the AclRule
                      host:
                        type: string
                      operation:
                        type: string
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Replace operation field with Enum
=======
>>>>>>> Update the AclRule
=======
>>>>>>> Regenerate YAML and doc after rebase
                        enum:
                        - Read
                        - Write
                        - Create
                        - Delete
                        - Alter
                        - Describe
                        - ClusterAction
                        - AlterConfigs
                        - DescribeConfigs
                        - IdempotentWrite
                        - All
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Update the AclRule
=======
>>>>>>> Replace operation field with Enum
=======
=======
>>>>>>> Update the AclRule
>>>>>>> Update the AclRule
=======
>>>>>>> Regenerate YAML and doc after rebase
                      resource:
                        type: object
                        properties:
                          name:
                            type: string
                          patternType:
                            type: string
                            enum:
                            - literal
                            - prefix
                          type:
                            type: string
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
                      resourcePatternType:
                        type: string
                        enum:
                        - literal
                        - prefix
                      topic:
                        type: string
>>>>>>> Add Authorization section to KafkaUser CRD
=======
>>>>>>> Update the AclRule
=======
                        required:
                        - name
>>>>>>> Replace operation field with Enum
=======
>>>>>>> Fields cannot be required
                      type:
                        type: string
                        enum:
                        - allow
                        - deny
                type:
                  type: string
              required:
              - acls
          required:
          - authentication
      required:
      - spec
