---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-topic-controller
  labels:
    app: strimzi
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: strimzi-topic-controller-role
  labels:
    app: strimzi
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: strimzi-topic-controller-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-topic-controller
roleRef:
  kind: ClusterRole
  name: strimzi-topic-controller-role
apiGroup: v1
---
apiVersion: v1
kind: Template
metadata:
  name: strimzi-topic-controller
  annotations:
    openshift.io/display-name: "Strimzi Topic Controller"
    description: >-
      This template creates a topic controller, which will synchronize
      certain ConfigMaps with the Kafka topics in a Strimzi Kafka cluster.
      For more information about using this template see http://strimzi.io
    tags: "messaging"
    iconClass: "fa fa-exchange"
    template.openshift.io/documentation-url: "http://strimzi.io"
parameters:
- name: KAFKA_BOOTSTRAP_SERVERS
  displayName: Kafka bootstrap servers
  description: DNS name and port of the Kafka node to connect to.
  required: true
  value: my-cluster-kafka:9092
- name: ZOOKEEPER_CONNECT
  displayName: Zookeeper connection info
  description: DNS name and port of the Zookeeper node to connect to.
  required: true
  value: my-cluster-zookeeper:2181
- name: ZOOKEEPER_SESSION_TIMEOUT
  displayName: Zookeeper session timeout
  description: The timeout for the topic controllers session with Zookeeper
  required: true
  value: 20seconds
- name: PERIODIC_INTERVAL
  displayName: The periodic reconciliation interval
  description: How frequently a full reconciliation should run
  required: true
  value: 10minutes
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: strimzi-topic-controller
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: strimzi-topic-controller
      spec:
        serviceAccountName: strimzi-topic-controller
        containers:
          - name: strimzi-topic-controller
            image: strimzi/topic-controller:latest
            env:
              - name: STRIMZI_CONFIGMAP_LABELS
                value: "strimzi.io/kind=topic"
              - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
                value: "${KAFKA_BOOTSTRAP_SERVERS}"
              - name: STRIMZI_ZOOKEEPER_CONNECT
                value: "${ZOOKEEPER_CONNECT}"
              - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT
                value: "${ZOOKEEPER_SESSION_TIMEOUT}"
              - name: STRIMZI_PERIODIC_INTERVAL
                value: "${PERIODIC_INTERVAL}"
              - name: STRIMZI_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            livenessProbe:
              httpGet:
                path: /healthy
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 30
---
apiVersion: v1
kind: Template
metadata:
  name: strimzi-topic
  annotations:
    openshift.io/display-name: "Apache Kafka Topic"
    description: >-
      This template creates a "Topic ConfigMap". Used in conjunction with
      the Strimzi topic controller this will create a corresponding
      topic in a Strimzi Kafka cluster.
      For more information about using this template see http://strimzi.io
    tags: "messaging"
    iconClass: "fa fa-exchange"
    template.openshift.io/documentation-url: "http://strimzi.io"
parameters:
- name: MAP_NAME
  displayName: Name of the ConfigMap
  description: Specifies the name of the ConfigMap. If possible this should be the same as the TOPIC_NAME parameter.
  required: true
  value: my-topic
- name: TOPIC_NAME
  displayName: Name of the topic
  description: Specifies the name of the topic in the Kafka cluster.
  required: true
  value: my-topic
- name: TOPIC_PARTITIONS
  displayName: Number of partitions
  description: The number of partitions in the created topic.
  required: true
  value: "1"
- name: TOPIC_REPLICAS
  displayName: Number of replicas
  description: The number of replicas in the created topic.
  required: true
  value: "1"
- name: TOPIC_CONFIG
  displayName: Topic config
  description: >-
    The topic config as a JSON map, for example: { "retention.ms":"345600000" }
    See https://kafka.apache.org/10/documentation/#topicconfigs for config key names and
    value syntax.
  required: true
  value: "{}"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "${MAP_NAME}"
    labels:
      strimzi.io/kind: topic
  data:
    name: "${TOPIC_NAME}"
    partitions: "${TOPIC_PARTITIONS}"
    replicas: "${TOPIC_REPLICAS}"
    config: "${TOPIC_CONFIG}"