sudo: required
language: java
notifications:
  email: false
jdk:
- oraclejdk8
services:
- docker
script: make
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: tE55qx6YYliNjdLaG2AYU03/pajS34fwsfUAlIjK4ONdrloZi6ffWqnwlnPHSEtq7TLmbRbosL0bkEjeNo0csz3XErBTrWe+wzygg9gKZQt8Pce7sL4Pccui4oGmrkNDnLN0i7M+EVovcSUCC7xxB3rRpPkL5ZOJ5aCIE5RdMacsZUy7tNqVJmW81KCiRkOo39RGgm0NL8lfDVo0Y7QDJ/VnKIxUP3yGCL5P9apOibhTATMlK2Mo7DWjZrKzSkwk0Tops+2zf7qh6m5SyuxQNprlGf0xY5DgoKWQHrPikhN8QVNKCTPyVKU2tONtnXksu2UQWb6mFXUzWR5V2xWEwePLcGMsnKFjSC4BB0onRZ9RiAL08d8UDynWMiV/7wc3P4C9sh+bhMu/mmw2BhZVUM2dwCmyIul3nCZyOM8Maf5oxeLygfvXeBLbz8DQFomAHZ520JaGsRboUOts4Z8X81RHEY5E3s5PCFqvt0570x6Bu/NAPEW+6MonQRb0Orym39Tc5TEpAudGigRaUG3CADxeaIw7b1/fTbif+scsomdfedx3syg4P+jKYp8F4KaqHj+o62nCpiN+NEX3ownEd0nkO3Aqc060xrS/gnGreVcdrxUDd5/H9xt8ynwmNi78Wx9kzUkbjoWkOU/s+F79On//7g6Q5uQEdPJdXl5ujz4=
  - secure: X/dobuJqd7Ihjc9YBPwAz1q2PAfCL2gJN1afU4Y0FfWTE6l7klNmUGQf8QhZdGHrISvY+OxJi79gcRHnAQqr6hNR43O11OAryU1ZIp5B3gb9lShTVMiAtF8Bu6EWzI4Hbeir5yPm8ne1wQCykXIrVVl/l3NnslJZ6NOz51cukyy2R0IEyE0JJUJsE2o+tIdSxsZ+cINUW+w6bLDn8oU5DowUQTp1LOU3NGK8iV38KUlusw+bSYNW+hjKmk8RPsqTRDtMJm04S7DM1s4A7W2/0Ty0+/NQ2PMTay4Bm1Qfc1ls/T9dTL4VluREVqGkW9iRLWANCRMbOBBf4zR1owx/rn3dtAR4VStCrEPxtfL6oE6Cxp/I0WCML5/C7aM08nNZHgb4C4UwV9qEjonIsG0/ZtB88qm0Y7+p0V/FHes+ldFjp3HKgj6c8G0LZ/vU1Dsh8E1SMTV/EOl0fRnYGKaVPhOHJqCGnGDhyhzdnhnR2VizM5M9W279bIe7352CsbV2ZKw2mIeDn5UMIoKirZHh8OzJfc+tKo9zU2u4upaXIlkzmb5rcqTVRT/GlsQFU0okMnRO9GY/GLbTHYmS5J0ZQpn+su+Y7UDccuZEnyeSdA08u1v0/CemsGPPJ0IP70Jf0lLWgzHE1syM5v+q9PDYdsqzGnwVKpu4sM2TyQZlHfY=
