sudo: required
language: java
notifications:
  email: false
jdk:
  - oraclejdk8
services:
  - docker
script: 
  - ./.travis/build.sh
env:
  global:
    - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
    - VERSION=${TRAVIS_COMMIT::8}
    - TAG=${TRAVIS_TAG:-latest}
    - BRANCH=${TRAVIS_BRANCH:-master}
    - DOCKER_ORG=enmasseproject
    - secure: t4hVkyJLKqs6wEx/Be9mT0TrgY/NKQ+KCUybOb97WNjyiuwd/dY9yWqvuVSw3dwWBiSj1lXadw6WTBydjwxQBayUAa0sKwFsTu6pNOK89AKQ+HkJQrSzYucT8TNRUOC0+PAWwkCTINa4/FLLlaWhmUMpELIlP5ozlqa+YyK86YZGXVOz8EHiVVyXOWLbS9Ebk2nUJ3yTn4wcqdjDAp1wZGNF9bspk7jsBJLTu4uRtVF4Kdn1KlVmut/0zCQo224r9UU+/HkVWYoBnI4i1izW1wZOdpK1e4siX7OnZ6TEzUOSH7by2R1wr32ejA/v8rU055yiA2aekm759GrKBw8Ofc7ZVcJiQrFCmsfHUlJj+7FIDW6qYM9U8L0l/6F38ZYOFDPYEx9d3kHZ6GlmhsuSUE3H0zoWXBd4PHNxy1fi5mUtYIKQGFUHGHRLTdIkkjzU4aMF8NYq+m+ZcOuSrqParEknvJxtaohXPbjW8/kIn3PjgnLt7V3Jf7n6nyjm7ZdxN2s1xHblF8JZK1gJ+oN1JkYkzvwMmUt89522nYIJd6hNLXG7T4Fhzh1XuGZY0ew7Omv08EFvgJgY5RWqhWlbXwW/fD9eHgsPIFAEUqENy4AD3gKLiMDyBLhPFwqT+0HUlYngJIeNdQCGnLkye+eAmlO/0sGjIQKrPWu80MtZvk8=
    - secure: Wu/aHaKn9zUjhu9GbZbCxS4vMoe7S3vZxuEChUAtulnTQK3WvYfckPU8B2JBVvp64JFfeVvBjpkfTM05KUZEUPcO6IddE5xqeWNUQBe6J2A2TCgKOTS4QC+x8MesVALm6EFHVtK9ODxN95ZeNydVCsm+AfF8J9X81XLDj9IkebwGX9bm+jtFT5EIcWsLs/kgeZ2vcJ6UE4zL07RKM8KqmV31YS/+13NfL+zavwKAy19e97q8+R2cfKSvA8UZuW9P1BjtT2FFR2NOxDf/Z08xLHpBzSVsO6jdJbTqVt0Gj2E8iLrQMrIijVD0iKIhULXA90+Vsi3WsrFCB1KsTJHV5b0VIoA7wkCmc0m1teVyW+2fF2FO0mR2qtIZ19+l10oCx3a2iGpHUaKee3DfFNJSvQWdwMSgg9f3qvhYjoY/trRSCpPOUb+hWmn0m4HPGKE5NSljyNijF7SXuFJpExCsTcgDuGkp9LMFriqkRlJsTQAIvj8UEMvlEJvgNIt7SQrHa9LeftEVQzBJFT0mucLcByPlatNFXUv5YGKIqIVulpmGDzit7UYSuNUM3dN9Nx4FDBlsAE9EeXYctNAaXQnA6h19raQixg9VnAH7si2lzA6Bi7poB4FydAiKwfIcIfqdSFcRhuOoukn1QUa+fjgTwHMSlq4s4Q17o2J+CLYuwoA=
