apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: minima.example.org
spec:
  group: example.org
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Minimum
    listKind: MinimumList
    singular: minimum
    plural: minima
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            constrained:
              type: integer
              minimum: 1
      required:
      - spec
