apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
spec:
  ports:
    - name: rest-api
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    name: kafka-connect
  type: ClusterIP
