apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-connect
  labels:
    name: kafka-connect
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
spec:
  ports:
    - port: 8083
      name: rest-api
      targetPort : 8083
      protocol: TCP
  selector:
    name: kafka-connect
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-connect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: enmasseproject/kafka-connect:latest
          ports:
            - name: rest-api
              containerPort: 8083
              protocol: TCP
          env:
            - name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
              value: "${KAFKA_CONNECT_BOOTSTRAP_SERVERS}"
            - name: KAFKA_CONNECT_GROUP_ID
              value: "${KAFKA_CONNECT_GROUP_ID}"
            - name: KAFKA_CONNECT_KEY_CONVERTER
              value: "${KAFKA_CONNECT_KEY_CONVERTER}"
            - name: KAFKA_CONNECT_VALUE_CONVERTER
              value: "${KAFKA_CONNECT_VALUE_CONVERTER}"
          volumeMounts:
            - mountPath: /opt/kafka/plugins-ext
              name: plugin-volume
          livenessProbe:
            httpGet:
              path: /
              port: rest-api
            initialDelaySeconds: 60
      initContainers:
          - name: plugin-loader
            image: ${IMAGE_REPO_NAME}/${IMAGE_NAME}-init-loader:latest
            env:
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: CONFIG_MAP
                value: "kafka-connect-plugins"
              - name: PLUGIN_PATH
                value: "/opt/kafka/plugins-ext"
            volumeMounts:
              - mountPath: /opt/kafka/plugins-ext
                name: plugin-volume
        volumes:
          - name: plugin-volume
            emptyDir: {}