version: 2
jobs:
  javabuild:
    environment:
      - MAVEN_OPTS: "-Xmx2048m"
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: strimzi-javabuild-{{ checksum "pom.xml" }}
      - run:
          name: Build code
          command: mvn clean -B -DskipTests package
      - save_cache:
          paths:
            - ~/.m2
          key: strimzi-javabuild-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - .m2
  javatest:
    environment:
      - MAVEN_OPTS: "-Xmx3072m"
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      #- checkout
      - attach_workspace:
          at: /home/circleci
      #- restore_cache:
      #    key: strimzi-javatest-{{ checksum "pom.xml" }}
      - run:
          name: Build code
          command: mvn -B -DskipITs verify  
      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: strimzi-javatest-{{ checksum "pom.xml" }}
  findbugs:
    environment:
      - MAVEN_OPTS: "-Xmx2048m"
      - MVN_ARGS:   "-B"
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /home/circleci
      #- restore_cache:
      #    key: strimzi-findbugs-{{ checksum "pom.xml" }}
      - run:
          name: Run findbugs
          command: make findbugs
      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: strimzi-findbugs-{{ checksum "pom.xml" }}
  docucheck:
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run docu check
          command: make docu_check
      - run:
          name: Build HTML docs
          command: make docu_html
      - run:
          name: Build HTML docs without header
          command: make docu_htmlnoheader
      - store_artifacts:
          path: /home/circleci/project/documentation/html
          destination: docs-html
      - store_artifacts:
          path: /home/circleci/project/documentation/htmlnoheader
          destination: docs-htmlnoheader
workflows:
  version: 2
  build-workflow:
    jobs:
      - javabuild
      - javatest:
          requires: 
            - javabuild
      - javatest:
          requires: 
            - javabuild
      - findbugs:
          requires: 
            - javabuild
      - docucheck:
          requires: 
            - javabuild