version: 2
jobs:
  javabuild:
    environment:
      - MAVEN_OPTS: "-Xmx2048m"
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: strimzi-javabuild-{{ checksum "pom.xml" }}
      - run:
          name: Build code
          command: mvn clean -B -DskipTests install
      - save_cache:
          paths:
            - ~/.m2
          key: strimzi-javabuild-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - .m2
  javatest:
    environment:
      - MAVEN_OPTS: "-Xmx2048m"
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run unit tests
          command: mvn -B -DskipITs verify  
  findbugs:
    environment:
      - MAVEN_OPTS: "-Xmx2048m"
      - MVN_ARGS:   "-B"
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run findbugs
          command: make findbugs
  changedderived:
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Check for changes in derived resources
          command: ./.circleci/changed-derived.sh
  docubuild:
    docker:
      - image: scholzj/circleci-centos-java:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run docu check
          command: make docu_check
      - run:
          name: Build HTML docs
          command: make docu_html
      - run:
          name: Build HTML docs without header
          command: make docu_htmlnoheader
      - store_artifacts:
          path: /home/circleci/project/documentation/html
          destination: docs-html
      - store_artifacts:
          path: /home/circleci/project/documentation/htmlnoheader
          destination: docs-htmlnoheader
workflows:
  version: 2
  build-workflow:
    jobs:
      - javabuild
      - docubuild
      - javatest:
          requires: 
            - javabuild
      - javatest:
          requires: 
            - javabuild
      - findbugs:
          requires: 
            - javabuild
      - changedderived:
          requires: 
            - javabuild