# Basic Kubernetes service & deployment
apiVersion: v1
kind: Service
metadata:
  name: grafana-openshift-server
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30130
  selector:
    app: grafana-openshift
    component: server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-openshift-server
  labels:
    app: grafana-openshift
    component: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-openshift
        component: server
    spec:
      containers:
      - image: strimzilabs/grafana-openshift:latest
        imagePullPolicy: IfNotPresent
        name: grafana-openshift-server
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
        env:
          - name: GF_INSTALL_PLUGINS
            value: hawkular-datasource
          - name: DATAD
            value: /usr/share/grafana/data
          - name: PLGND
            value: /usr/share/grafana/data/plugins
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /usr/share/grafana/data
      volumes:
        - name: grafana-data
          emptyDir: {}
