apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: strimzi-cluster-controller-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-controller
roleRef:
  kind: Role
  name: strimzi-cluster-controller-role
  apiGroup: rbac.authorization.k8s.io
