# Triggers
trigger:
  branches:
    include:
      - 'master'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

jobs:
  - job: 'strimzi_build_and_test'
    displayName: 'Build & Test'
    # Strategy for the job
    strategy:
      matrix:
        'java-8':
          image: 'Ubuntu-18.04'
          jdk_version: '1.8'
          jdk_path: '/usr/lib/jvm/java-8-openjdk-amd64'
        'java-11':
          image: 'Ubuntu-18.04'
          jdk_version: '11'
          jdk_path: '/usr/lib/jvm/java-11-openjdk-amd64'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: $(image)
    # Environment variables
    variables:
      - template: "templates/default_variables.yaml"
    # Pipeline steps
    steps:
      - template: "templates/general_steps.yaml"

      - bash: ".azure/scripts/build.sh"
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASS: $(DOCKER_PASS_SECRET)
          MVN_ARGS: '-B -Dsurefire.rerunFailingTestsCount=5 -Dfailsafe.rerunFailingTestsCount=2'
        displayName: "Build images"

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: "Unit & Integration tests"
        condition: always()



