# Triggers
trigger:
  branches:
    include:
      - 'master'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

jobs:
  - job: 'strimzi_build_and_test'
    displayName: 'Build & Test'
    # Strategy for the job
    strategy:
      matrix:
        'java-8':
          image: 'Ubuntu-18.04'
          jdk_version: '1.8'
          jdk_path: '/usr/lib/jvm/java-8-openjdk-amd64'
        'java-11':
          image: 'Ubuntu-18.04'
          jdk_version: '11'
          jdk_path: '/usr/lib/jvm/java-11-openjdk-amd64'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: $(image)
    # Environment variables
    variables:
      - template: "templates/default_variables.yaml"
    # Pipeline steps
    steps:
      - template: 'templates/setup_java.yaml'
        parameters:
          JDK_PATH: $(jdk_path)
          JDK_VERSION: $(jdk_version)

      - template: "templates/log_variables.yaml"

      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.4'
          addToPath: true

      - bash: gem install asciidoctor
        displayName: 'Install asciidoctor'

      - bash: ".azure/scripts/setup_docker.sh"
        displayName: "Setup Docker environment"

      - template: "templates/build_strimzi.yaml"

      - bash: ".travis/install_yq.sh"
        displayName: "Install yq"

      - bash: ".travis/setup-kubernetes.sh"
        displayName: "Setup Minikube cluster"

      - bash: ".azure/scripts/build.sh"
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASS: $(DOCKER_PASS_SECRET)
          MVN_ARGS: '-B'
        displayName: "Build images"

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: "Unit & Integration tests"
        condition: always()



