# Triggers
# This pipeline will be trigger by github command /azp pull-request-pipeline
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

jobs:
  - job: 'strimzi_build_and_systemtest'
    displayName: 'Build & Systemtest'
    # Strategy for the job
    strategy:
      matrix:
        'java-11':
          image: 'Ubuntu-18.04'
          jdk_version: '11'
          jdk_path: '/usr/lib/jvm/java-11-openjdk-amd64'
    # Base system
    pool:
      vmImage: 'Ubuntu-18.04'
    # Environment variables
    variables:
      - template: 'templates/default_variables.yaml'
    # Set timeout for jobs
    timeoutInMinutes: 300
    # Pipeline steps
    steps:
      - template: 'templates/setup_java.yaml'
        parameters:
          JDK_PATH: $(jdk_path)
          JDK_VERSION: $(jdk_version)

      - template: "templates/log_variables.yaml"

      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          dockerVersion: 19.03.9
          releaseType: stable

      - bash: ".azure/scripts/setup_shellcheck.sh"
        displayName: "Setup Shellcheck"

      - bash: ".travis/install_yq.sh"
        displayName: "Install yq"

      - bash: ".travis/setup-kubernetes.sh"
        displayName: "Setup Minikube cluster"

      - bash: ".travis/setup-helm.sh"
        displayName: "Setup Helm"
        env:
          TEST_HELM2_VERSION: 'v2.16.3'
          TEST_HELM3_VERSION: 'v3.2.0'

      - template: "templates/build_strimzi.yaml"

      - bash: |
          make docker_build
          make docker_tag
        env:
          MVN_ARGS: '-B -DskipTests'
        displayName: "Build Strimzi images locally"

      - task: Maven@3
        inputs:
          mavenPomFile: 'systemtest/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: 'default'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/failsafe-reports/TEST-*.xml'
          goals: 'verify'
          options: '-Dgroups=acceptance -DexcludedGroups=flaky,loadbalancer -Dmaven.javadoc.skip=true -B -V -Dfailsafe.rerunFailingTestsCount=2'
        env:
          OPERATOR_IMAGE_PULL_POLICY: "IfNotPresent"
        displayName: 'Run systemtests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          searchFolder: "systemtest"
          testRunTitle: "System tests"
        condition: always()

      - bash: |
          rm -rf systemtest/target/logs/timeMeasuring
        displayName: 'Remove timeMeasuring dir from logs'
        condition: failed()

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'systemtest/target/logs/'
          artifactName: systemtest-logs
        displayName: 'Publish logs from failed tests'
        condition: failed()



