# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'
      -
# Regression tests are split into 5 jobs because of timeout set to 360 minutes for each job
jobs:
  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_kafka'
      display_name: 'regression-bundle I. - kafka'
      test_case: 'kafka.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_connect_security'
      display_name: 'regression-bundle II. - connect + security'
      test_case: 'connect.*ST,security.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_operators_rollingupdate_watcher'
      display_name: 'regression-bundle III. - operator + rollingupdate + watcher'
      test_case: 'operators.*ST,rollingupdate.*ST,watcher.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_mirrormaker'
      display_name: 'regression-bundle IV. - mirrormaker'
      test_case: 'mirrormaker.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_all_remaining'
      display_name: 'regression-bundle V. - remaining system tests'
      # !LoggingChangeST is skipped because it can be flaky on Azure
      test_case: '!kafka.*ST,!mirrormaker.*ST,!connect.*ST,!security.*ST,!LoggingChangeST,!operators.*ST,!rollingupdate.*ST,!watcher.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360
