apiVersion: v1
kind: Service
metadata:
  name: strimzi-convert-webhook
  labels:
    app: strimzi
spec:
  selector:
    name: strimzi-crd-upgrade
    strimzi.io/kind: strimzi-crd-upgrade
  ports:
    - protocol: TCP
      name: https
      port: 8443
      targetPort: 8443
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080