apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-crd-upgrade
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-crd-upgrade
      strimzi.io/kind: strimzi-crd-upgrade
  template:
    metadata:
      labels:
        name: strimzi-crd-upgrade
        strimzi.io/kind: strimzi-crd-upgrade
    spec:
      serviceAccountName: strimzi-convert-webhook
      volumes:
        - name: keys-certs
          secret:
            secretName: strimzi-convert-webhook
      containers:
        - name: strimzi-cluster-operator
          image: tjbentley/crd-convert:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
#          args:
#            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: keys-certs
              mountPath: /opt/strimzi/config/
          env:
            - name: LOG_LEVEL
              value: DEBUG
            - name: PLAIN_PORT
              value: "8080"
            - name: TLS_PORT
              value: "8443"
            - name: KEYSTORE
              value: /opt/strimzi/config/server-key.pem
            - name: CERTSTORE
              value: /opt/strimzi/config/server.crt
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
  strategy:
    type: Recreate
