---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topics.kafka.strimzi.io
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Topic
    listKind: TopicList
    singular: topic
    plural: topics
  validation:
    openAPIV3Schema:
      properties:
        partitions:
          type: integer
        replicas:
          type: integer
          minimum: 1
          maximum: 32767
        config:
          type: object
        additionalProperties:
          type: object
        topicName:
          type: string
