apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-global
  labels:
    app: strimzi
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
# Persistent Volumes can be resized only when it is supported in the storage class.
# Therefore we need the ability to get the storage class details and we require this access right.
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
