apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaBridge
metadata:
  name: bridge
spec:
  replicas: 1
  kafka:
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  image: strimzi/kafka-bridge:latest
  http:
    port: 8080
 

