---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-topic-controller
  labels:
    app: strimzi
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: strimzi-topic-controller-role
  labels:
    app: strimzi
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: strimzi-topic-controller-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-topic-controller
roleRef:
  kind: Role
  name: strimzi-topic-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-topic-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-topic-controller
    spec:
      serviceAccountName: strimzi-topic-controller
      containers:
        - name: strimzi-topic-controller
          image: strimzi/topic-controller:latest
          env:
            - name: STRIMZI_CONFIGMAP_LABELS
              value: "strimzi.io/kind=topic"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka:9092
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: my-cluster-zookeeper:2181
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT
              value: 20seconds
            - name: STRIMZI_PERIODIC_INTERVAL
              value: 10minutes
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
