apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  # used 3 replicas in order to have alwayas majority for leader election
  replicas: 3
  template:
    metadata:
      labels:
        name: kafka
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: kafka
          image: "enmasseproject/kafka-statefulsets:latest"
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/
      volumes:
        - name: kafka-storage
          emptyDir: {}
