apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 9092
      name: kafka
      targetPort : 9092
      protocol: TCP
  clusterIP: None
  selector:
    name: kafka
