apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: zookeeper
          image: "enmasseproject/zookeeper:latest"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper
      volumes:
        - name: zookeeper-storage
          emptyDir: {}
