apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper-headless"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "enmasseproject/zookeeper:latest"
          ports:
            - name: clientport
              containerPort: 2181
              protocol: TCP
            - containerPort: 2888
              name: clustering
              protocol: TCP
            - containerPort: 3888
              name: leaderelection
              protocol: TCP
          env:
            - name: ZOOKEEPER_NODE_COUNT
              value: "1"
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper
          livenessProbe:
            exec:
              command:
              - "/opt/zookeeper/zookeeper_healthcheck.sh"
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - "/opt/zookeeper/zookeeper_healthcheck.sh"
            initialDelaySeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: zookeeper-storage
          emptyDir: {}
