{{- if .Values.createGlobalResources -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.strimzi.io
  labels:
    app: '{{ template "strimzi.name" . }}'
    chart: '{{ template "strimzi.chart" . }}'
    component: kafkatopics.kafka.strimzi.io-crd
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Partitions
      description: The desired number of partitions in the topic
      jsonPath: .spec.partitions
      type: integer
    - name: Replication factor
      description: The desired number of replicas of each partition
      jsonPath: .spec.replicas
      type: integer
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            properties:
              partitions:
                type: integer
                minimum: 1
              replicas:
                type: integer
                minimum: 1
                maximum: 32767
              config:
                type: object
              topicName:
                type: string
            required:
              - partitions
              - replicas
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              observedGeneration:
                type: integer
  - name: v1alpha1
    served: true
    storage: false
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Partitions
      description: The desired number of partitions in the topic
      jsonPath: .spec.partitions
      type: integer
    - name: Replication factor
      description: The desired number of replicas of each partition
      jsonPath: .spec.replicas
      type: integer
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            properties:
              partitions:
                type: integer
                minimum: 1
              replicas:
                type: integer
                minimum: 1
                maximum: 32767
              config:
                type: object
              topicName:
                type: string
            required:
              - partitions
              - replicas
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              observedGeneration:
                type: integer
  scope: Namespaced
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    singular: kafkatopic
    plural: kafkatopics
    shortNames:
    - kt
    categories:
    - strimzi
{{- end -}}
