{{- if .Values.createGlobalResources -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkaclusterrebalances.kafka.strimzi.io
  labels:
    app: '{{ template "strimzi.name" . }}'
    chart: '{{ template "strimzi.chart" . }}'
    component: kafkaclusterrebalances.kafka.strimzi.io-crd
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaClusterRebalance
    listKind: KafkaClusterRebalanceList
    singular: kafkaclusterrebalance
    plural: kafkaclusterrebalances
    shortNames:
    - kcr
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            goals:
              type: array
              items:
                type: string
            verbose:
              type: boolean
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  lastTransitionTime:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
            observedGeneration:
              type: integer
            sessionId:
              type: string
            optimizationResult:
              type: object
{{- end -}}
