apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  version: 2.6.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: connect-metrics
        key: metrics-config.yml

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connect-metrics
  labels:
    app: strimzi
data:
  metrics-config.yml: '{"lowercaseOutputLabelNames":true,"lowercaseOutputName":true,"rules":[{"help":"Kafka
              $1 JMX metric start time seconds","labels":{"clientId":"$2"},"name":"kafka_$1_start_time_seconds","pattern":"kafka.(.+)<type=app-info,
              client-id=(.+)><>start-time-ms","type":"GAUGE","valueFactor":0.001},{"help":"Kafka
              $1 JMX metric info version and commit-id","labels":{"$3":"$4","clientId":"$2"},"name":"kafka_$1_$3_info","pattern":"kafka.(.+)<type=app-info,
              client-id=(.+)><>(commit-id|version): (.+)","type":"GAUGE","value":1},{"help":"Kafka
              $1 JMX metric type $2","labels":{"clientId":"$3","partition":"$5","topic":"$4"},"name":"kafka_$2_$6","pattern":"kafka.(.+)<type=(.+)-metrics,
              client-id=(.+), topic=(.+), partition=(.+)><>(.+-total|compression-rate|.+-avg|.+-replica|.+-lag|.+-lead)","type":"GAUGE"},{"help":"Kafka
              $1 JMX metric type $2","labels":{"clientId":"$3","topic":"$4"},"name":"kafka_$2_$5","pattern":"kafka.(.+)<type=(.+)-metrics,
              client-id=(.+), topic=(.+)><>(.+-total|compression-rate|.+-avg)","type":"GAUGE"},{"help":"Kafka
              $1 JMX metric type $2","labels":{"clientId":"$3","nodeId":"$4"},"name":"kafka_$2_$5","pattern":"kafka.(.+)<type=(.+)-metrics,
              client-id=(.+), node-id=(.+)><>(.+-total|.+-avg)","type":"UNTYPED"},{"help":"Kafka
              $1 JMX metric type $2","labels":{"clientId":"$3"},"name":"kafka_$2_$4","pattern":"kafka.(.+)<type=(.+)-metrics,
              client-id=(.*)><>(.+-total|.+-avg|.+-bytes|.+-count|.+-ratio|.+-age|.+-flight|.+-threads|.+-connectors|.+-tasks|.+-ago)","type":"GAUGE"},{"help":"Kafka
              Connect JMX Connector status","labels":{"connector":"$1","status":"$3","task":"$2"},"name":"kafka_connect_connector_status","pattern":"kafka.connect<type=connector-task-metrics,
              connector=(.+), task=(.+)><>status: ([a-z-]+)","type":"GAUGE","value":1},{"help":"Kafka
              Connect JMX metric type $1","labels":{"connector":"$2","task":"$3"},"name":"kafka_connect_$1_$4","pattern":"kafka.connect<type=(.+)-metrics,
              connector=(.+), task=(.+)><>(.+-total|.+-count|.+-ms|.+-ratio|.+-avg|.+-failures|.+-requests|.+-timestamp|.+-logged|.+-errors|.+-retries|.+-skipped)","type":"GAUGE"},{"help":"Kafka
              Connect JMX metric $1","labels":{"connector":"$1"},"name":"kafka_connect_worker_$2","pattern":"kafka.connect<type=connect-worker-metrics,
              connector=(.+)><>([a-z-]+)","type":"GAUGE"},{"help":"Kafka Connect JMX metric
              worker","name":"kafka_connect_worker_$1","pattern":"kafka.connect<type=connect-worker-metrics><>([a-z-]+)","type":"GAUGE"},{"help":"Kafka
              Connect JMX metric rebalance information","name":"kafka_connect_worker_rebalance_$1","pattern":"kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+)","type":"GAUGE"}]}'

