apiVersion: v1
kind: ConfigMap
metadata:
  name: my-connect-cluster
  labels:
    strimzi.io/kind: cluster
    strimzi.io/type: kafka-connect-s2i
data:
  nodes: "1"
  healthcheck-delay: "60"
  healthcheck-timeout: "5"
  connect-config: |-
    {
      "bootstrap.servers": "my-cluster-kafka:9092",
      "group.id": "my-connect-cluster",
      "offset.storage.topic": "my-connect-cluster-offsets",
      "config.storage.topic": "my-connect-cluster-configs",
      "status.storage.topic": "my-connect-cluster-status",
      "key.converter": "org.apache.kafka.connect.json.JsonConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "key.converter.schemas.enable": true,
      "value.converter.schemas.enable": true,
      "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter",
      "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "internal.key.converter.schemas.enable": false,
      "internal.value.converter.schemas.enable": false,
      "config.storage.replication.factor": 3,
      "offset.storage.replication.factor": 3,
      "status.storage.replication.factor": 3
    }
